import { Inter } from 'next/font/google';
// import './globals.css';
// import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import Header from './component/includes/Header';
import Sidebar from './component/includes/Sidebar';
import Footer from './component/includes/Footer';
import Script from 'next/script';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
        <meta http-equiv='X-UA-Compatible' content='IE=edge' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta
          name='description'
          content='Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.'
        />
        <meta
          name='keywords'
          content='admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app'
        />
        <meta name='author' content='pixelstrap' />
        <link
          rel='icon'
          href='/assets/images/favicon.png'
          type='image/x-icon'
        />
        <link
          rel='shortcut icon'
          href='/assets/images/favicon.png'
          type='image/x-icon'
        />
        <title>Cuba - Premium Admin Template</title>
        {/* <!-- Google font--> */}
        <link
          href='https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap'
          rel='stylesheet'
        />
        <link
          href='https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap'
          rel='stylesheet'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/font-awesome.css'
        />
        {/* <!-- ico-font--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/icofont.css'
        />
        {/* <!-- Themify icon--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/themify.css'
        />
        {/* <!-- Flag icon--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/flag-icon.css'
        />
        {/* <!-- Feather icon--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/feather-icon.css'
        />
        {/* <!-- Plugins css start--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/slick.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/slick-theme.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/scrollbar.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/animate.css'
        />
        {/* <!-- Plugins css Ends--/> */}
        {/* <!-- Bootstrap css--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/vendors/bootstrap.css'
        />
        {/* <!-- App css--/> */}
        <link rel='stylesheet' type='text/css' href='/assets/css/style.css' />
        <link
          id='color'
          rel='stylesheet'
          href='/assets/css/color-1.css'
          media='screen'
        />
        {/* <!-- Responsive css--/> */}
        <link
          rel='stylesheet'
          type='text/css'
          href='/assets/css/responsive.css'
        />
      </head>
      <body className={inter.className}>
        {/* <!-- loader starts--> */}
        {/* <div className='loader-wrapper'>
          <div className='loader-index'>
            {' '}
            <span></span>
          </div>
          <svg>
            <defs></defs>
            <filter id='goo'>
              <fegaussianblur
                in='SourceGraphic'
                stddeviation='11'
                result='blur'
              ></fegaussianblur>
              <fecolormatrix
                in='blur'
                values='1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9'
                result='goo'
              >
                {' '}
              </fecolormatrix>
            </filter>
          </svg>
        </div> */}
        {/* <!-- loader ends--> */}
        {/* <!-- tap on top starts--> */}
        <div className='tap-top'>
          <i data-feather='chevrons-up'></i>
        </div>
        {/* <!-- tap on tap ends--> */}
        {/* <!-- page-wrapper StartMy Currencies--> */}
        <div className='page-wrapper compact-wrapper' id='pageWrapper'>
          <Header />
          {/* <!-- Page Body Start--> */}
          <div className='page-body-wrapper'>
            <Sidebar />
            {children}
            {/* <!-- footer start--> */}
            <Footer />
          </div>
        </div>

        {/* <!-- latest jquery--> */}
        <Script src='/assets/js/jquery.min.js'></Script>
        {/* <!-- Bootstrap js--> */}
        {/* <Script src='/assets/js/bootstrap/bootstrap.bundle.min.js'></Script> */}
        {/* <!-- feather icon js--> */}
        <Script src='/assets/js/icons/feather-icon/feather.min.js'></Script>
        <Script src='/assets/js/icons/feather-icon/feather-icon.js'></Script>
        {/* <!-- scrollbar js--> */}
        <Script src='/assets/js/scrollbar/simplebar.js'></Script>
        <Script src='/assets/js/scrollbar/custom.js'></Script>
        {/* <!-- Sidebar jquery--> */}
        <Script src='/assets/js/config.js'></Script>
        {/* <!-- Plugins JS start--> */}
        <Script src='/assets/js/sidebar-menu.js'></Script>
        <Script src='/assets/js/sidebar-pin.js'></Script>
        <Script src='/assets/js/slick/slick.min.js'></Script>
        <Script src='/assets/js/slick/slick.js'></Script>
        <Script src='/assets/js/header-slick.js'></Script>
        <Script src='/assets/js/chart/apex-chart/apex-chart.js'></Script>
        <Script src='/assets/js/chart/apex-chart/stock-prices.js'></Script>
        <Script src='/assets/js/dashboard/dashboard_4.js'></Script>
        {/* <!-- Plugins JS Ends--> */}
        {/* <!-- Theme js--> */}
        <Script src='/assets/js/script.js'></Script>
        <Script src='/assets/js/theme-customizer/customizer.js'></Script>
      </body>
    </html>
  );
}
